---
- name: Intitialize deploy and gather facts
  deploy_helper:
    path: '{{deploy.path}}'
    keep_releases: '{{deploy.keep_releases | default(3)}}'
    current_path: current
    releases_path: releases
    shared_path: shared
    state: present

- name: Clone git repository
  git:
    repo: '{{deploy.git_repository}}'
    dest: '{{deploy_helper.new_release_path}}'

- name: Add unfinished file
  file:
    path: '{{deploy_helper.new_release_path}}/{{deploy_helper.unfinished_file_name}}'
    state: touch

# Perform app stuff

- name: Finilize deploy
  deploy_helper:
    path: '{{deploy.path}}'
    release: '{{deploy_helper.new_release}}'
    state: finalize
