---
- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present
  
- name: Install Nginx
  become: yes
  apt: pkg=nginx state=latest update_cache=true

- name: Change default nginx site
  become: yes
  template: src=default.tpl dest=/etc/nginx/sites-available/default
  notify: restart nginx
