---
server:
    install: '1'
    packages: [git, vim, pkg-config, libssl-dev]
    timezone: Europe/Berlin
    locale: de_DE.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: api.perna.dev, ip: 192.168.33.99, memory: '1024', sharedfolder: ./.., useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant/app/public
    servername: api.perna.dev
    php_socket: /var/run/php/php7.0-fpm.sock
mongodb:
    install: '1'
php:
    install: '1'
    ppa: php-7.0
    packages: [php7.0-cli, php7.0-intl, php7.0-mcrypt]
    peclpackages: [mongodb]
