---
- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/php

- name: Ensure packages database is up to date
  become: yes
  apt: update_cache=yes

- name: Install php
  become: yes
  apt: pkg="{{php_version}}" state=latest

- name: Install php-fpm
  become: yes
  apt: pkg="{{php_version}}-fpm" state=latest

- name: Install PHP Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items: '{{php.packages}}'
  when: php.packages is defined

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- include: xdebug.yml
- include: configure.yml
- include: pecl.yml
