- name: Install php-dev
  apt: pkg="{{php_version}}-dev" state=present
  when: php.peclpackages is defined

- name: Install Package
  shell: echo "\n\n\n\n\n\n\n\n\n" | pecl install {{ item }}
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"
  with_items: php.peclpackages
  when: php.peclpackages is defined

- name: Create extension .ini file
  template: >
    src="extension.tpl"
    dest="{{php_config_prefix}}/mods-available/{{ item }}.ini"
    owner="root"
    group="root"
    mode=0644
  with_items: php.peclpackages
  when: php.peclpackages is defined

- name: Enable extension
  shell: "{% if php_version == 'php5' %}php5enmod{% else %}phpenmod{% endif %} {{ item }}"
  with_items: php.peclpackages
  when: php.peclpackages is defined
