---
- name: MongoDB | Fetch 10Gen signing key
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

- name: MongoDB | Add 10Gen repository
  shell:
    echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list
    creates=/etc/apt/sources.list.d/10gen.list

- name: MongoDB | Install latest MongoDB release
  apt: pkg=mongodb-10gen state=present update_cache=yes

- name: MongoDB | Create default configuration template
  template:
    src=mongodb.conf.tpl
    dest=/etc/mongodb.conf
    owner=root group=root mode=0644
  notify:
    - mongodb-restart

- name: MongoDB | Insure deamon is running correctly
  service: name=mongodb state=started

- name: MongoDB | Install pip package manager
  apt:
    name: python-pip
    state: present

- name: MongoDB | Install pymongo
  pip:
    name: pymongo
    version: 2.4.2

- name: MongoDB | Create Database and User
  mongodb_user:
    database: '{{mongodb.database}}'
    user: '{{mongodb.user}}'
    password: '{{mongodb_password}}'